### your site title here

title: Diana Pham
description: subtitle | affiliations | motto

baseurl: /0xdpham.github.io #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "https://twitter.com/the_phamasaur"
linkedin: "#"
stackoverflow: "https://meta.stackexchange.com/users/1278430/dpham"
github: "https://github.com/0xdpham"
researchgate: "https://www.researchgate.net/profile/Diana-Pham-3"
orcid: "https://orcid.org/0000-0002-3785-2333"
quora: "#"
instagram: "#"
facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
